### ISSUE TITLE
Checking out a remote branch leads to detached state 

### ISSUE THREAD

**Issue by domiSchenk** [Commandos-app/Commandos#41]
- [ ] Check the name of the associated remote url
- [ ] when reading branches save the branch Name and the full name

**Comment by florianbaer** [comment]
Questions:
- This needs to be done in the `checkout` command of commandos?
- What do you mean with _Check the name of the associated remote url_ ?
> When reading branches save the branch Name and the full name
 - Save where?

**Comment by florianbaer** [comment]
![image](https://user-images.githubusercontent.com/3041156/136658171-f4c1409a-bab1-4422-97d4-82708b638e85.png)
Other issue when starting it with `cmd.exe`

**Comment by domiSchenk** [comment]
Maybe a reboot after rust install will help.
